---
title: "Cytoscape Network Charts"
output: 
  rmarkdown::github_document:
    html_preview: false
  html_document:
    keep_md: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cytoscape)
library(dplyr)
library(jsonlite)

```

A HTMLWidget wrapper for the [Cytoscape.js](http://js.cytoscape.org/) graph / network visualisation and analysis library.

## A Minimal Example


```{r min}

nodes <- data.frame(id = c('a','b'))
edges <- data.frame(id = 'ab', source = 'a', target = 'b')

cytoscape(nodes = nodes, edges = edges) 

```


## Styling Edges and Nodes

```{r style1, fig.width=10}

ct <- cytoscape(nodes = nodes, edges = edges)

ct %>% node_style('background-color' = '#ff0000')

```


```{r style2}

ct %>% edge_style('line-color' = '#ff0000')

```


## With Real Data

Comtrade waste plastic exports for December 2017.

```{r plastics}


df <- cytoscape::comtrade

nodes <- data.frame(id = unique(c(df$reporter, df$partner)), stringsAsFactors = FALSE)
edges <- df %>%
    dplyr::select(source = reporter,
                  target = partner) %>%
    dplyr::mutate(id = paste(source, '_', target))
           
cytoscape(nodes = nodes, edges = edges) %>% 
  layout('grid', rows = 4)

cytoscape(nodes = nodes, edges = edges) %>% 
  layout('breadthfirst', directed = TRUE)


```


## With Geographic Location

```{r location, fig.width=12}

# n_loc <- nodes %>%
#   dplyr::do(cbind(., ggmap::geocode(.$id)))

coords <- cytoscape::coords %>%
  rename(x = lon,
         y = lat) %>%
  filter(id != 'World') %>%
  mutate_at('y', funs(-.))
edges <- filter(edges, 
                source %in% coords$id,
                target %in% coords$id)

cytoscape(nodes = coords, edges = edges) %>% 
  layout('preset') %>%
  node_style(width = 3, height = 3, 'font-size' = 8) %>%
  edge_style(width = 1)

```


